name: Static analysis

on: pull_request

jobs:

  clang-tidy:
    runs-on: ubuntu-22.04

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bear \
          clang-tidy \
          libcppunit-dev \
          libcurl4-openssl-dev \
          libncurses-dev \
          zlib1g-dev

    - uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Fetch base branch
      run: |
        git remote add upstream "https://github.com/${{ github.event.pull_request.base.repo.full_name }}"
        git fetch --no-tags --no-recurse-submodules upstream "${{ github.event.pull_request.base.ref }}"

    - name: Configure monorepo
      run: |
        autoreconf -fiv
        ./configure

    - name: Build with bear
      run: |
        bear -- make -j$(nproc)

    - name: Create results directory
      run: mkdir clang-tidy-result

    - name: Analyze
      run: |
        git diff -U0 "$(git merge-base HEAD "upstream/${{ github.event.pull_request.base.ref }}")" \
          | clang-tidy-diff -p1 -path . -export-fixes clang-tidy-result/fixes.yml \
            "-extra-arg=-include${PWD}/config.h"

    - name: Save PR metadata
      run: |
        echo "${{ github.event.number }}" > clang-tidy-result/pr-id.txt
        echo "${{ github.event.pull_request.head.repo.full_name }}" > clang-tidy-result/pr-head-repo.txt
        echo "${{ github.event.pull_request.head.sha }}" > clang-tidy-result/pr-head-sha.txt

    - uses: actions/upload-artifact@v4
      with:
        name: clang-tidy-result
        path: clang-tidy-result/
