name: Unit tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-24.04
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcppunit-dev \
          libcurl4-openssl-dev \
          zlib1g-dev \
          libncurses-dev \
          liblua5.3-dev \
          lua5.3

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build monorepo
      run: |
        autoreconf -fiv
        ./configure --with-lua
        make -j$(nproc)

    - name: Test rtorrent
      run: make check

    - name: Archive test logs (rtorrent)
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: rtorrent-test-suite.log
        path: test/test-suite.log

    - name: Archive test logs (libtorrent)
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: libtorrent-test-suite.log
        path: test/libtorrent/test-suite.log

  ubuntu-variants:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        config_flag: ["--with-xmlrpc-c", "--with-xmlrpc-tinyxml2"]
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcppunit-dev \
          libcurl4-openssl-dev \
          zlib1g-dev \
          libxmlrpc-c++8-dev \
          libncurses-dev \
          liblua5.3-dev \
          lua5.3

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: |
        autoreconf -fiv
        ./configure ${{ matrix.config_flag }}
        make -j$(nproc)

    - name: Test rtorrent
      run: make check

  macos:
    needs: ubuntu
    runs-on: macos-latest
    env:
      TEST_IGNORE_SIGNAL_INTERRUPT_LATENCY: "YES"
    steps:
    - name: Install Dependencies
      run: |
        brew install automake autoconf libtool cppunit curl

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: |
        autoreconf -fiv
        ./configure
        make -j$(sysctl -n hw.logicalcpu)

    - name: Test rtorrent
      run: make check

  alpine:
    needs: ubuntu
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: ['x86_64']
    defaults:
      run:
        shell: alpine.sh {0}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: jirutka/setup-alpine@v1
      with:
        branch: edge
        arch: ${{ matrix.platform }}
        packages: >
          build-base automake autoconf cppunit-dev curl-dev
          libtool linux-headers ncurses-dev openssl-dev pkgconf zlib-dev
    - name: Build and Test
      run: |
        autoreconf -fiv
        ./configure
        grep LT_SMP_CACHE_BYTES config.h
        make -j$(nproc)
        make check
