name: Static analysis

on: pull_request

jobs:

  unit-tests:
    runs-on: ubuntu-22.04

    steps:
    - name: Update Packages
      run: |
        sudo apt-get update
    - name: Install Dependencies
      run: |
        sudo apt-get install -y \
          libcppunit-dev \
          libcurl4-openssl-dev
    - name: Fetch libtorrent
      run: |
        git clone https://github.com/rakshasa/libtorrent
    - name: Build libtorrent
      run: |
        cd libtorrent
        libtoolize
        aclocal -I scripts
        autoconf -i
        autoheader
        automake --add-missing
        ./configure
        make
        sudo make install
        cd ..
        rm -rf libtorrent
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Fetch base branch
      run: |
        git remote add upstream "https://github.com/${{ github.event.pull_request.base.repo.full_name }}"
        git fetch --no-tags --no-recurse-submodules upstream "${{ github.event.pull_request.base.ref }}"
    - name: Configure Project
      run: |
        libtoolize
        aclocal -I scripts
        autoconf -i
        autoheader
        automake --add-missing
        ./configure
    - name: Build Project
      run: |
        make
    - name: Run Unit Tests
      run: |
        ls /usr/local/lib/
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
        make check
    - name: Archive test/test-suite.log
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-suite.log
        path: test/test-suite.log
